# Workflow ini akan melakukan build dan testing terhadap development app.
name: Dev Testing 🔎 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing
    environment: dev-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "MINIO_DEV_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" > .env
          echo "MINIO_DEV_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_DEV_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env

      - name: Build and Run Container
        run: |
          sudo docker compose up --build --detach pacmusic-dev

      - name: Hit Endpoint
        run: |
          sleep 20
          curl localhost:5000
      
      - name: Install Python dependencies
        run: |
          pip install -r test/requirements.txt

      - name: Testing
        run: |
          python3 test/test.py
